language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t xrchitron/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true xrchitron/react-test npm test

after_success:
  - docker build -t xrchitron/multi-client ./client
  - docker build -t xrchitron/multi-nginx ./nginx
  - docker build -t xrchitron/multi-server ./server
  - docker build -t xrchitron/multi-worker ./worker
  #Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push them to docker hub
  - docker push xrchitron/multi-client
  - docker push xrchitron/multi-nginx
  - docker push xrchitron/multi-server
  - docker push xrchitron/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'ap-northeast-1'
  app: 'multi-docker'
  env: 'Mutli-docker-env'
  bucket_name: 'elasticbeanstalk-ap-northeast-1-343534424551'
  bucket_path: 'docker-multi'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY